### CASE 01

### hello
GET http://localhost:8080/case01



### CASE 02

### MyResourceNotFoundException
GET http://localhost:8080/case02

### CustomHandlerExceptionResolver
GET http://localhost:8080/case02/2



### CASE 03

### ControllerAdvice
GET http://localhost:8080/case03

### ControllerAdvice2
GET http://localhost:8080/case03Another



### CASE 04

### ResponseStatusException
GET http://localhost:8080/case04

###